apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-server  # Match the label with the deployment name
  template:
    metadata:
      labels:
        app: node-server  # Correct the label to match the deployment name
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"  # Assuming your Node.js application listens on port 8080
    spec:
      containers:
      - name: node-server
        imagePullPolicy: Always
        image: myaakoub/node-server:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: '8080'
          - name: REDIS_URL
            value: redis://redis.default.svc.cluster.local:6379
          - name: REDIS_REPLICAS_URL
            value: redis://redis.default.svc.cluster.local:6379

